apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/samhdd/oracle-gitops-lab'
    targetRevision: HEAD
    path: 'helm/my-nginx'  # this is your Helm chart directory
    helm:
      valueFiles:
        - values.yaml       # optional, if you're using custom values
      skipCrds: false       # set to true if you want to skip CRDs

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'my-application-namespace'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
